Catch up py-six-current with master [manual merge resolution] (#657)
* Add crc32c instructions for enterprise SUSE

* Fixes #390. (#602)

We use oauth2client, which has mechanisms in place to fall back to "pure
Python crypto" in the absence of pyOpenSSL -- additionally, this crypto lib is
only used for service account credential functionality. In those cases,
users would sometimes see the error:

AssertionError: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()

Random.atfork() should be called in both the parent and child process after
launching a new child process.

* Don't clobber local files with differing size (#605)

As discussed in #591, `gsutil cp -n` will overwrite an existing local
file if its size differs from the size of the source file.  This
behavior is contrary to user expectations, POSIX convention, and the
documentation.

Remove the special case for files with differing size, which was added
in a768a58 to support resuming partial downloads.  This code has not
been useful since 3e3d6dc, which started using temporary files (named
with _.gstmp) for all downloads.

Fixes: #591

Signed-off-by: Kevin Locke <kevin@kevinlocke.name>

* Bump six version from 1.9.0 to 1.12.0. (#607)

This allows us to pick up `ensure_text`, `ensure_binary`, etc. functions,
which will be helpful for the Python 2 -> "six" (2 and 3) migration
we're currently working on.

Bumped the version in setup.py and checked out the 1.12.0 tag from our
mirror, via `cd third_party/six; git fetch --tags origin; git checkout
1.12.0`.

* Adds support for Bucket Policy Only feature.

Adds support for Bucket Policy Only via its own stand-alone command as
well as additions to mb and ls commands.

Internal tracking bug: https://issuetracker.google.com/issues/67957525

* Updates helptext for bucketpolicyonly command. (#608)

The old text was never changed after the command was revised to have two
subcommands. These changes make the explanations correct, as well as
isolating helptext between `get` and `set` so that `gsutil help bucketpolicyonly
get` and `gsutil help bucketpolicyonly set` will return only the appropriate
segments of the helptext.

* 4.36 Release Notes.

* Update CHECKSUM and VERSION for 4.36 release.

* Update crcmod install instructions for CentOS 6 (#612)

CentOS 6 uses Python 2.6 by default (at least, it does on our GCE images). This updates the instructions to show steps necessary to enable Python 2.7 for a session, as well as compiling/installing crcmod for Python 2.7.

This addresses https://issuetracker.google.com/issues/63114773

* Remove metadata fetch in bpo set (#618)

Update `bucketpolicyonly set` implementation to no longer fetch bucket metadata before patching.

* Fix du output spacing for 6-digit sizes (#624)

Fixes #613.

* Add ps1 script to run integ. tests in parallel (#625)

See script details for why this is necessary.

This cuts runtime down from over an hour (running serially with
one process) to ~25 minutes.

* Fix spelling in .PARAMETER part of docstring

* Don't run `gcloud compute` commands on CI envs. (#627)

Perfdiag shouldn't run these commands on CI environments because we
probably (or at least, shouldn't) have permission to read/access
their compute resource metadata.

* Updated travis to unit test Python 3.5+ (#628)

In anticipation of our upcoming Python 3.x support, this commit
adds support to have Travis run unit tests for versions of Python
greater than or equal to 3.5.

These versions are allowed to fail since we don't yet have full
support for Python 3.x. This file may be updated after we release
compatibility to the main branch.

`fail_fast` attribute was added so that Travis won't block PR
approval during allowed failures.

* Fixes #606 - use SNI for boto cxns if possible (#631)

Boto https connections weren't using SNI before. With the recent-ish
introduction of OpenSSL 1.1.1, we start to see SSL errors when making
requests to storage.googleapis.com (GCS's XML API) where the server
hostname was not specified. This pulls in
https://github.com/boto/boto/pull/3843 as a hotfix into gsutil, since
there isn't a released version of Boto where this PR is included yet,
and we'd like to have it sooner rather than later.

* 4.37 Release Notes. (#632)

* Update CHECKSUM and VERSION for 4.37 release.

* Added Kokoro integ test scripts. (#642)

This scripts have been moved into this repository for Kokoro
to run on its VMs each time a PR is submitted. These files were
moved into GitHub due to GCP VMs not having Piper access, per
b/123369015#comment13

* Added config generator for CI test scripts. (#643)

* Added config generator for CI test scripts.

Added a shell script to be called by Kokoro when running
integration tests. It generates a config file allowing access
to the bigstore-gsutil-testing account.

Like the integ test shell scripts, this was pulled from Google3
due to GCP Kokoro VMs being unable to access Piper.

* Added build configs, removed symlinks. (#644)

Added build configs for Kokoro to use. Removed symlinks, I was
mistaken about those. Moved Matt's powershell script into the
Kokoro directly.

* Spacing fixes for docs, based on last release. (#646)

These fixes allow us to *correctly* generate web docs from the source
documentation.

* Vendor in Boto repository (#645)

* Add logic to prepend gsutil/third_party/vendored to sys.path

Prepend third_party/vendored directory before third_party root
directory in path. This ensures packages that are vendored in
have precidence over their third_party counterparts.

The vendored subdir will contain dependencies that we have made
changes to that may not yet exist in their upstream repositories.
We are beginning with the boto library which we need to add
compatibility changes to, but it may take some time before the
boto maintainers can make a new release.

* Cloned boto/boto repo to vendored directly, not as submodule.

* Added details for Bucket Policy Only for defacl get. (#649)

Currently, when getting the default object ACL, the description only suggests either the caller doesn't have OWNER permission or the bucket has private ACLs.

This add information about Bucket Policy Only as one of the possible reasons that default object ACL is empty.

* Kokoro builds now fetch keys from Keystore (#648)

Before executing build scripts, Kokoro will now fetch keys from
keystore. Keys are stored in /src/keystore and should include a
key to access bigstore-gsutil-testing GCP account for access to
our testing infra, and a GitHub access key for Kokoro to monitor
and comment on our gsutil repository.

Docs: go/kokoro-keystore
ACLs: cl/236744745
Bug:  b/127358637

* Remove boto from git submodules. (#650)

* Remove boto from git submodules.

* Also fix setup.py.

* Added param configs for Kokoro Windows jobs (#651)

Testing powershell script needs the Python path and gsutil directory
specified in its parameters. We're doing this in the build config
for Windows.

Build params kokoro doc: go/kokoro-build-params

* Explicit wording in rm docs about deleting buckets (#647)

* Fix docs formatting to convert to better HTML. (#654)

These changes seem to make Sphinx happy, and I'm tired of dealing with
all the manual fixes to generated HTML docs.

* Additional checks around ShouldProhibitMultiprocessing() (#656)

User reporting that this check crashes in FreeDesktop:
https://github.com/GoogleCloudPlatform/gsutil/issues/655
Cause: this check assumes that the first line is the correct line with
'NAME="<linux ver>"'. In most cases, this is correct, however this
assumption cannot be relied upon. Additional checks around the contents
of each line were added to look for 'NAME='.

Generic exception added to catch any other issues from this method in
the future (with exception information added to logging).