Fixes #390.
We use oauth2client, which has mechanisms in place to fall back to "pure
Python crypto" in the absence of pyOpenSSL -- additionally, this crypto lib is
only used for service account credential functionality. In those cases,
users would sometimes see the error:

AssertionError: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()

Random.atfork() should be called in both the parent and child process after
launching a new child process.