Catch up py-six-current with master (#615)
* Add crc32c instructions for enterprise SUSE

* Fixes #390. (#602)

We use oauth2client, which has mechanisms in place to fall back to "pure
Python crypto" in the absence of pyOpenSSL -- additionally, this crypto lib is
only used for service account credential functionality. In those cases,
users would sometimes see the error:

AssertionError: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()

Random.atfork() should be called in both the parent and child process after
launching a new child process.

* Don't clobber local files with differing size (#605)

As discussed in #591, `gsutil cp -n` will overwrite an existing local
file if its size differs from the size of the source file.  This
behavior is contrary to user expectations, POSIX convention, and the
documentation.

Remove the special case for files with differing size, which was added
in a768a58 to support resuming partial downloads.  This code has not
been useful since 3e3d6dc, which started using temporary files (named
with _.gstmp) for all downloads.

Fixes: #591

Signed-off-by: Kevin Locke <kevin@kevinlocke.name>

* Bump six version from 1.9.0 to 1.12.0. (#607)

This allows us to pick up `ensure_text`, `ensure_binary`, etc. functions,
which will be helpful for the Python 2 -> "six" (2 and 3) migration
we're currently working on.

Bumped the version in setup.py and checked out the 1.12.0 tag from our
mirror, via `cd third_party/six; git fetch --tags origin; git checkout
1.12.0`.

* Adds support for Bucket Policy Only feature.

Adds support for Bucket Policy Only via its own stand-alone command as
well as additions to mb and ls commands.

Internal tracking bug: https://issuetracker.google.com/issues/67957525

* Updates helptext for bucketpolicyonly command. (#608)

The old text was never changed after the command was revised to have two
subcommands. These changes make the explanations correct, as well as
isolating helptext between `get` and `set` so that `gsutil help bucketpolicyonly
get` and `gsutil help bucketpolicyonly set` will return only the appropriate
segments of the helptext.

* 4.36 Release Notes.

* Update CHECKSUM and VERSION for 4.36 release.

* Update crcmod install instructions for CentOS 6 (#612)

CentOS 6 uses Python 2.6 by default (at least, it does on our GCE images). This updates the instructions to show steps necessary to enable Python 2.7 for a session, as well as compiling/installing crcmod for Python 2.7.

This addresses https://issuetracker.google.com/issues/63114773