storage_url: Remove a trailing dot in an exception message
This is consistent with other exception messages.

Because a dot is appended when the exception is printed to the user [1],
this prints two dots instead of one:

    InvalidUrlError: . is an invalid root-level object name..

[1]: https://github.com/GoogleCloudPlatform/gsutil/blob/adf221296/gslib/__main__.py#L576