Show acceptable scope suggestions from the HTTP response to users for 403s due to insufficient_scope.
Example output:

$ gsutil config -s https://www.googleapis.com/auth/bigquery
$ gsutil ls gs://

AccessDeniedException: 403 Insufficient OAuth2 scope to perform this operation.
Acceptable scopes: https://www.googleapis.com/auth/cloud-platform