Merge master branch into py-six-current (#699)
* Add crc32c instructions for enterprise SUSE

* Fixes #390. (#602)

We use oauth2client, which has mechanisms in place to fall back to "pure
Python crypto" in the absence of pyOpenSSL -- additionally, this crypto lib is
only used for service account credential functionality. In those cases,
users would sometimes see the error:

AssertionError: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()

Random.atfork() should be called in both the parent and child process after
launching a new child process.

* Don't clobber local files with differing size (#605)

As discussed in #591, `gsutil cp -n` will overwrite an existing local
file if its size differs from the size of the source file.  This
behavior is contrary to user expectations, POSIX convention, and the
documentation.

Remove the special case for files with differing size, which was added
in a768a58 to support resuming partial downloads.  This code has not
been useful since 3e3d6dc, which started using temporary files (named
with _.gstmp) for all downloads.

Fixes: #591

Signed-off-by: Kevin Locke <kevin@kevinlocke.name>

* Bump six version from 1.9.0 to 1.12.0. (#607)

This allows us to pick up `ensure_text`, `ensure_binary`, etc. functions,
which will be helpful for the Python 2 -> "six" (2 and 3) migration
we're currently working on.

Bumped the version in setup.py and checked out the 1.12.0 tag from our
mirror, via `cd third_party/six; git fetch --tags origin; git checkout
1.12.0`.

* Adds support for Bucket Policy Only feature.

Adds support for Bucket Policy Only via its own stand-alone command as
well as additions to mb and ls commands.

Internal tracking bug: https://issuetracker.google.com/issues/67957525

* Updates helptext for bucketpolicyonly command. (#608)

The old text was never changed after the command was revised to have two
subcommands. These changes make the explanations correct, as well as
isolating helptext between `get` and `set` so that `gsutil help bucketpolicyonly
get` and `gsutil help bucketpolicyonly set` will return only the appropriate
segments of the helptext.

* 4.36 Release Notes.

* Update CHECKSUM and VERSION for 4.36 release.

* Update crcmod install instructions for CentOS 6 (#612)

CentOS 6 uses Python 2.6 by default (at least, it does on our GCE images). This updates the instructions to show steps necessary to enable Python 2.7 for a session, as well as compiling/installing crcmod for Python 2.7.

This addresses https://issuetracker.google.com/issues/63114773

* Remove metadata fetch in bpo set (#618)

Update `bucketpolicyonly set` implementation to no longer fetch bucket metadata before patching.

* Fix du output spacing for 6-digit sizes (#624)

Fixes #613.

* Add ps1 script to run integ. tests in parallel (#625)

See script details for why this is necessary.

This cuts runtime down from over an hour (running serially with
one process) to ~25 minutes.

* Fix spelling in .PARAMETER part of docstring

* Don't run `gcloud compute` commands on CI envs. (#627)

Perfdiag shouldn't run these commands on CI environments because we
probably (or at least, shouldn't) have permission to read/access
their compute resource metadata.

* Updated travis to unit test Python 3.5+ (#628)

In anticipation of our upcoming Python 3.x support, this commit
adds support to have Travis run unit tests for versions of Python
greater than or equal to 3.5.

These versions are allowed to fail since we don't yet have full
support for Python 3.x. This file may be updated after we release
compatibility to the main branch.

`fail_fast` attribute was added so that Travis won't block PR
approval during allowed failures.

* Fixes #606 - use SNI for boto cxns if possible (#631)

Boto https connections weren't using SNI before. With the recent-ish
introduction of OpenSSL 1.1.1, we start to see SSL errors when making
requests to storage.googleapis.com (GCS's XML API) where the server
hostname was not specified. This pulls in
https://github.com/boto/boto/pull/3843 as a hotfix into gsutil, since
there isn't a released version of Boto where this PR is included yet,
and we'd like to have it sooner rather than later.

* 4.37 Release Notes. (#632)

* Update CHECKSUM and VERSION for 4.37 release.

* Added Kokoro integ test scripts. (#642)

This scripts have been moved into this repository for Kokoro
to run on its VMs each time a PR is submitted. These files were
moved into GitHub due to GCP VMs not having Piper access, per
b/123369015#comment13

* Added config generator for CI test scripts. (#643)

* Added config generator for CI test scripts.

Added a shell script to be called by Kokoro when running
integration tests. It generates a config file allowing access
to the bigstore-gsutil-testing account.

Like the integ test shell scripts, this was pulled from Google3
due to GCP Kokoro VMs being unable to access Piper.

* Added build configs, removed symlinks. (#644)

Added build configs for Kokoro to use. Removed symlinks, I was
mistaken about those. Moved Matt's powershell script into the
Kokoro directly.

* Spacing fixes for docs, based on last release. (#646)

These fixes allow us to *correctly* generate web docs from the source
documentation.

* Vendor in Boto repository (#645)

* Add logic to prepend gsutil/third_party/vendored to sys.path

Prepend third_party/vendored directory before third_party root
directory in path. This ensures packages that are vendored in
have precidence over their third_party counterparts.

The vendored subdir will contain dependencies that we have made
changes to that may not yet exist in their upstream repositories.
We are beginning with the boto library which we need to add
compatibility changes to, but it may take some time before the
boto maintainers can make a new release.

* Cloned boto/boto repo to vendored directly, not as submodule.

* Added details for Bucket Policy Only for defacl get. (#649)

Currently, when getting the default object ACL, the description only suggests either the caller doesn't have OWNER permission or the bucket has private ACLs.

This add information about Bucket Policy Only as one of the possible reasons that default object ACL is empty.

* Kokoro builds now fetch keys from Keystore (#648)

Before executing build scripts, Kokoro will now fetch keys from
keystore. Keys are stored in /src/keystore and should include a
key to access bigstore-gsutil-testing GCP account for access to
our testing infra, and a GitHub access key for Kokoro to monitor
and comment on our gsutil repository.

Docs: go/kokoro-keystore
ACLs: cl/236744745
Bug:  b/127358637

* Remove boto from git submodules. (#650)

* Remove boto from git submodules.

* Also fix setup.py.

* Added param configs for Kokoro Windows jobs (#651)

Testing powershell script needs the Python path and gsutil directory
specified in its parameters. We're doing this in the build config
for Windows.

Build params kokoro doc: go/kokoro-build-params

* Explicit wording in rm docs about deleting buckets (#647)

* Fix docs formatting to convert to better HTML. (#654)

These changes seem to make Sphinx happy, and I'm tired of dealing with
all the manual fixes to generated HTML docs.

* Additional checks around ShouldProhibitMultiprocessing() (#656)

User reporting that this check crashes in FreeDesktop:
https://github.com/GoogleCloudPlatform/gsutil/issues/655
Cause: this check assumes that the first line is the correct line with
'NAME="<linux ver>"'. In most cases, this is correct, however this
assumption cannot be relied upon. Additional checks around the contents
of each line were added to look for 'NAME='.

Generic exception added to catch any other issues from this method in
the future (with exception information added to logging).

* Updated Kokoro build script paths. (#659)

Build paths all have a typo, per b/127678469#comment7. This is
preventing Kokoro builds.

* Added continuous build configs (#663)

* Added continuous build configs

Added Kokoro CI build configs to trigger every time a push happens
on our repository. Although this will largely overlap with the
presubmit tests running on every PR, it may help us in the case of
code being pushed directly to the repo without a PR.

* Adjusted CI test timeouts.

* Move vendored directory into gslib. (#666)

With our last couple of CLs to start vendoring boto, we overlooked that
our setup.py was excluding packages under the top-level third_party
directory.  This moves the vendored libraries to gslib/vendored so that
they're always included with the gslib code, even for pip installs.

This also cleans up some of the logic around having to guess whether we
were using boto that came with a pip installation or a packaged
installation.

* Updated keystore key name (#668)

In configs, fetching the GCP account key is mistakenly referencing
the keystore config name rather than the key name.

Our keystore keys can be found at go/gsutil-keystore-keyname

* Use our fork of boto as a submodule. (#669)

This enables us to more easily contribute changes we make back to the
upstream boto library -- if we make them in our fork, all we have to do
is submit a PR to the upstream, and we'll also instantly be able to update
gsutil to pull in the latest commits from our fork.

This was done via:
$ rm -rf gslib/vendored/boto
$ git rm -r gslib/vendored/boto
$ git submodule add git://github.com/gsutil-mirrors/boto.git gslib/vendored/boto

* Update storage_v1_* apitools generated modules. (#670)

This change updates the JSON API client files in
gslib/third_party/storage_apitools to be consistent with the source
documents (via the JSON API discovery doc) and updates docstrings to
the new style that apitools generates (using raw strings), which makes
this change a bit noisy.

This commit also adds the "includeTrailingDelimiter" field to some
message types, but that is uninteresting because it's unused in the
code.

* Added configs for child jobs (#672)

Added these configs so we can inject specific environment variables
into each child job, namely which Python version to use.

See: go/kokoro-env-vars

* Removed `type` and `group_spec` from build configs (#677)

These were leftover when making the build configs based on the job
configs. It turns out that build configs don't have attributes for
type or group spec, only job configs.

Sponge log where we spotted this issue:
go/pr-remove-type-group-spec-sponge-log

Kokoro build proto:
go/kokoro-build

* Prepended continuous config to child configs (#678)

* Prepended continuous config to child configs

Child build configs don't inherit from the build config defining
their job, so I'm manually prepending the needed fields.

Sponge logs: go/sponge-needs-build-file-prepend-pr
Sed command used to update these:
`find . -type f -name 'py*.cfg' -exec sed -i -e '1rcontinuous.cfg' -e
'1{h;d}' -e '2{x;G}'  {} \;`

* Updated `GsutilRepoDir` path.

This enviroment variable had a typo in it. This corrects the typo.

* Updating build script path to a relative path. (#679)

* Updating build script path to a relative path.

* Fixed path in comment.

* Relative path updated to not use ./ (#680)

Kokoro evenually concatenates the relative path with the path its
tracking. Using the ./file notation, we started getting errors like:
`/tmp/workspace/workspace/cloud_storage_gsutil/linux/py27_json/src/github/./run_integ_tests.sh`

Removed instances of `./file` with just `file` using find -exec sed:
`find . -type f -name '*.cfg' -exec sed -i
's|\"./run_integ_tests|\"run_integ_tests|g' {} \;`

* Add support for conditions in IAM policy bindings. (#682)

This change allows `gsutil iam get` to successfully parse and print out
IAM policies for buckets/objects that contain conditions in their policy
bindings. It also allows setting such policies via `gsutil iam set`.
Finally, it prohibits `gsutil iam ch` from interacting with any such
resources (even if the desired bindings changes contain no conditions),
and presents an error message to users that instructs them to instead use
"iam get", followed by editing the policy and then using "iam set".

Note for internal devs: These behaviors have been manually tested against
our test environment. See the log at go/paste/6015417187303424.

I've disabled the tests for the time being (to make our release test and CI
tests happy), and will re-enable them once all projects are whitelisted to use
the new conditions functionality.

This change also documents two additional boto config settings that we
were using but not making any note of.

* Documentation typo fixes (#684)

Fix two typos reported by users over in the c.g.c pages.

* Updated .boto config path in environment variables. (#685)

.boto config files are now found in the path
/tmpfs/src/.boto_[json|xml]

These files were updated with find -exec sed:

`find . -type f -name '*.cfg' -exec sed -i
's|/src/config/.boto_json|/tmpfs/src/.boto_json|g' {} \;`

`find . -type f -name '*.cfg' -exec sed -i
's|/src/config/.boto_xml|/tmpfs/src/.boto_xml|g' {} \;`

* Print trace in debug mode for rsync sync failures (#686)

In the event of a failure (e.g. due to encoding oddities), the only
thing you currently see is a one-line summary of the error. Seeing
exactly where the error came from would be more helpful for debugging.

* Update limits on compose operations (#689)

Several of the limits around compose operations were lifted a few months ago.

* Fix description of the progress indicator bar (#690)

The behavior has changed slightly over time, and the current documentation doesn't quite match the current behavior.

* Bunch of small doc fixes. (#688)

* Update prod.py

* Update cp.py

* Update versions.py

* Update web.py

* Update acl.py

* Update versioning.py

* Update stat.py

* Update stat.py

* Bump vendored boto lib to newest commit. (#694)

Done via `cd gslib/vendored/boto; git pull`.

Also remove some monkeypatches that we now have in our vendored
version of boto

*  Updated Mac and Linux CI scripts and configs to working status. (#695)

* Updated Linux CI scripts and configs to working status.

This PR reflects commits to `ci-testing` branch where I performed
several iterations of testing on our CI scripts and configs.
These broad refactors should allow Linux CI to run tests on
manual invokations.

* Mac test script symlinks to Linux test script

They use identical logic now. Making the Mac script a symlink
so we only have to maintain one script for both OSes. Also,
bumped processes to 8.

* Removed leading tabs before config definition.

* Updated BOTO_CONFIG environment variable to API

Environment variables specifying the boto config path were replaced with the API the tests should target, i.e. JSON or XML.

Previously we were deriving the API from the current job's Boto config path. The config path is always the same though, and could vary by VM, so it makes sense for us to do the inverse, specifying the API from Kokoro, and choosing the correct config file path based on the given API.

These changes were done with find -exec sed:
`find . -type f -name '*.cfg' -exec sed -i 's|BOTO_CONFIG|API|g' {} \;`
`find . -type f -name '*.cfg' -exec sed -i 's|/tmpfs/src/.boto_xml|.boto_xml|g' {} \;`
`find . -type f -name '*.cfg' -exec sed -i 's|/tmpfs/src/.boto_json|.boto_json|g' {} \;`

This PR accompanies cl/239702660

* Replaced '.boto_[xml|json]' with just [xml|json]

* Removed duplicate test